name:                 Practica05
version:              0.1.0.0
visibility:           public
id:                   Practica05-0.1.0.0-inplace
key:                  Practica05-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           eduardovar1090@ciencias.unam.mx
author:               EduardoVrP
abi:                  inplace
exposed:              True
exposed-modules:      Practica05 Terminos
import-dirs:
    "/home/xiro/Documentos/2026/4to semestre/LoComp/haskellPractice/LC2026-2-Practica05/dist-newstyle/build/x86_64-linux/ghc-9.4.8/Practica05-0.1.0.0/build"

library-dirs:
    "/home/xiro/Documentos/2026/4to semestre/LoComp/haskellPractice/LC2026-2-Practica05/dist-newstyle/build/x86_64-linux/ghc-9.4.8/Practica05-0.1.0.0/build"

library-dirs-static:
    "/home/xiro/Documentos/2026/4to semestre/LoComp/haskellPractice/LC2026-2-Practica05/dist-newstyle/build/x86_64-linux/ghc-9.4.8/Practica05-0.1.0.0/build"

dynamic-library-dirs:
    "/home/xiro/Documentos/2026/4to semestre/LoComp/haskellPractice/LC2026-2-Practica05/dist-newstyle/build/x86_64-linux/ghc-9.4.8/Practica05-0.1.0.0/build"

data-dir:
    "/home/xiro/Documentos/2026/4to semestre/LoComp/haskellPractice/LC2026-2-Practica05/."

hs-libraries:         HSPractica05-0.1.0.0-inplace
depends:              base-4.17.2.1
haddock-interfaces:
    "/home/xiro/Documentos/2026/4to semestre/LoComp/haskellPractice/LC2026-2-Practica05/dist-newstyle/build/x86_64-linux/ghc-9.4.8/Practica05-0.1.0.0/doc/html/Practica05/Practica05.haddock"

haddock-html:
    "/home/xiro/Documentos/2026/4to semestre/LoComp/haskellPractice/LC2026-2-Practica05/dist-newstyle/build/x86_64-linux/ghc-9.4.8/Practica05-0.1.0.0/doc/html/Practica05"
